### ISSUE TITLE
Restrict Game Messages so only "accepted" players can post

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#50]
Overview
===
Once #30 is complete where players can join a game, the Game Messages tab should prevent players from creating new messages unless they have a status of `accepted` or `game-master`.

Requirements
===
Any user (logged in our out) should be able to view the Game Messages tab and all its content. 
The "Add Message" component should only be displayed to those users that are accepted to the Game, and the Game Creator. 

For all other users, we'll display a friendly text message. 

> While games are viewable by everyone, only players are able to post game messages. Try posting a message in the Lounge, or searching for another open game.

**Comment by mikelax** [comment]
@nazar I see that the `meQuery` exposes info about the logged in user, and is used on the almost finished page. Can I use that same query here for the game players / messages components? I see where the `meQuery` is used in the exported compose but what is that actually doing? Is it setting the user info on the state?  

edit: After looking at the almost finished page I can't figure out what the meQuery is used for.

**Comment by nazar** [comment]
Hey @mikelax!

>Can I use that same query here for the game players / messages components? 

The [myGamePlayer](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/queries.js#L173-L180) might be better here as it returns `game_players` for the currently logged in user against specific games - this would save us from having to match the current user's db id against all `game_players` in a game.

>I see where the meQuery is used in the exported compose but what is that actually doing? Is it setting the user info on the state?

Yes.

>edit: After looking at the almost finished page I can't figure out what the meQuery is used for.

The `meQuery` injects the user's details into `props.data` [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Login/AlmostFinished/index.js#L35-L38) to be used by the form.

I've also experimented with the `meQuery` to inject the current user into a redux store but have not yet used this and might not as it is easier to just use the `meQuery` via Apollo rather than Redux - I'll probably end up removing that code.

HTH

**Comment by mikelax** [comment]
Thanks @nazar
What determines that the data from the meQuery is added to the props at the object location 
This.props.data.me.*

**Comment by nazar** [comment]
https://www.apollographql.com/docs/react/basics/queries.html#default-result-props

Which is set [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Login/AlmostFinished/index.js#L249).

Generally the `graphql` injects the query details into `props` as `props.data.[object name]` unless `graphql` is passed the `name` option then the query results will be available as `props.[name].[graphql object]`.

In `props.data.[object name]`, `object name` is derived from the query name. In this instance it is `me` from [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/queries/users.js#L21).

HTH
