### ISSUE TITLE
Only original user should be able to edit message

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#68]
Overview
===
Currently any logged in user is able to edit a lounge or game message. this should be refactored so only the user that created the message should be able to edit.

**Comment by mikelax** [comment]
@nazar  this is the issue I was talking about this morning where I think we may need the userId on the UI, or at least some other way to handle this situation. 

We need to lock down the "edit" functionality, and perhaps eventually delete of both lounge and game messages to only the user that created them. Currently any logged in user can edit. We *may* also allow at some point the GM to edit, but I don't see that needed for a v1. 

Should we change the response (model in api) to send down another attribute of something like `canModify` which will check to see if the current user owns the messages. If so set the value to true, false otherwise?

**Comment by nazar** [comment]
> this is the issue I was talking about this morning where I think we may need the userId on the UI, or at least some other way to handle this situation.

I was thinking about the pros/cons of exposing the user ids in the UI and I think I might have been to paranoid. It is a lot easier for the UI logic if we just expose the user.id in the UI for logic such as this.

I think the simplest way to handle this for now is to make the current `user.id` available in the UI. Good news is that the [me](https://github.com/mikelax/forgingadventures/blob/master/client/src/queries/users.js#L5) UI query already includes _your_ user id. The gameLoungeMessages array [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/View/components/GameLoungeMessages.js#L43) already includes the user object in this [query](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/queries.js#L48) we just need to add the extra line for `id` in there to expose the gameLoungeMessage's owner `user.id` [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/View/components/GameLoungeMessages.js#L116). The only thing left to do in that component is to add the `me` query [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/View/components/GameLoungeMessages.js#L221) to make the current user available in that component for the user.id comparison for the `edit` control.

The same logic can also be applied to the gameMessage - you'll just need to add the `user` graphQL object [here](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/queries.js#L29) so that it is available in the [GameMessages](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/View/components/GameMessages.js) component.

The only thing we need to take of (and I could do this) is to check that the current user id equals the message user id in the API on the [message update mutation](https://github.com/mikelax/forgingadventures/blob/master/api/schemas/gameLounge.js#L64).

HTH!
