### ISSUE TITLE
On new user signup, after almost finished, menu doesn't refresh

### ISSUE THREAD

**Issue by mikelax** [mikelax/forgingadventures#84]
Overview
===
This issues relates to work done in #80. 
After a new user signup, the user is taken to the almost finished page. They go through and fill out this form, after submitting they are taken to the /games page. 
The issue is that the dropdown menu that displays the username doesn't update until a full page refresh. This should update after the almost finish page is saved. 

For this test I didn't upload a profile image, so it displayed the default Auth0 profile image, but this should also update.

**Comment by mikelax** [comment]
@nazar  if you want to point me in the direction of how to link the menu to getting updated after the form save I can tackle this ticket.

**Comment by nazar** [comment]
Hey @mikelax - without looking into at at depth I suspect the issue is related to the `meQuery` needing to be refreshed after the `login/almost-done` submit mutation. I think we did something similar when [creating a game](https://github.com/mikelax/forgingadventures/blob/master/client/src/components/Games/Create/index.js#L194-L196).
